### ISSUE TITLE
Trasa: dodatkowe uwagi - brak przewijania okienka edycji

### ISSUE THREAD

**Issue by jakobos** [zaquncio/rejony-app#100]
W informacjach o trasie w zakładce "Dodatkowe uwagi" po dodaniu odnośnika znika możliwość przewijania okna.

**Comment by duzymaju** [comment]
Mogę prosić screen'a?

**Comment by jakobos** [comment]
![obraz](https://cloud.githubusercontent.com/assets/25006353/24296473/8ce2b538-109f-11e7-964e-999083b66a19.png)

Przed dodaniem odnośnika da się przewijać tekst.


![obraz](https://cloud.githubusercontent.com/assets/25006353/24296514/ae949516-109f-11e7-9ae9-63af223006ec.png)

Po dodaniu odnośnika brak możliwości przewijania -> nie da się kliknąć "Zapisz" bo jest niewidoczny.

**Comment by duzymaju** [comment]
Załatwione: #104.
