### ISSUE TITLE
Usuwanie rejonu: nie działa anulowanie komunikatu przyciskiem [x]

### ISSUE THREAD

**Issue by sigma1810** [zaquncio/rejony-app#14]
1. Wchodzę w szczegóły zgłoszonego przeze mnie rejonu.
2. Z MENU wybieram opcję [Usuń].

Próba wybrania przycisku [x] na wyświetlonym oknie w celu anulowania komunikatu nie zamyka okna (bug).

Proszę o naprawę przycisku [x] lub jego usunięcie (mamy opcję [Anuluj]).
![screen](https://cloud.githubusercontent.com/assets/24360424/22761134/be2df4b2-ee59-11e6-9eb4-09f07cf17457.png)

**Comment by duzymaju** [comment]
Poprawione: #78.
