### ISSUE TITLE
Błąd przy próbie usunięcia dodanego rejonu

### ISSUE THREAD

**Issue by sigma1810** [zaquncio/rejony-app#15]
W sekcji 'Moje zgłoszenia' mam zgłoszony rejon.
1. Wchodzę w szczegóły mojego rejonu i wybieram usuń, potwierdzam przyciskiem [Zaiste, usuń] (1.png).
![1](https://cloud.githubusercontent.com/assets/24360424/22761522/648a7578-ee5b-11e6-9733-dcdc2ba56cb6.png)
2. Pojawia się komunikat błędu jak na (2.png) <-- BUG.
![2](https://cloud.githubusercontent.com/assets/24360424/22761547/7fe1f512-ee5b-11e6-8a18-ed2bdc4b5f93.png)
3. Po ponownym wejściu do sekcji 'Moje zgłoszenia' okazuje się, że rejon został usunięty (3.jpg).
![3](https://cloud.githubusercontent.com/assets/24360424/22761571/9a60001e-ee5b-11e6-8e1e-9ea15c245f3e.png)

Proszę o usunięcie komunikatu błędu z '2.png' (zakładam, że skoro opcja 'Usuń' jest dostępna, to nieprawidłowym zachowaniem jest komunikat błędu).

**Comment by zaquncio** [comment]
Proszę nie testować na środowisku produkcyjnym do testów przeznaczona jest instancja beta.edk.org.pl. Testowanie na środowisku na którym pracują rejony jest bardzo dużym zagrożeniem.

**Comment by duzymaju** [comment]
Naprawione: #75.
