### ISSUE TITLE
Pilne. Błąd przy próbie wejścia w trasy.

### ISSUE THREAD

**Issue by jakobos** [zaquncio/rejony-app#18]
W przestrzeni rejonu, po kliknięciu w Rejon/Trasy wyświetla Error 500.

**Comment by zaquncio** [comment]
Dzieje się to tylko dla rejonu, który jest pierwszy raz w EDK?

**Comment by jakobos** [comment]
Na pewno w tych które są pierwszy raz, nie wiem czy w innych też.

**Comment by jakobos** [comment]
Naprawione
