### ISSUE TITLE
Zmiana adresu e-mail - anglojęzyczny komunikat błędu

### ISSUE THREAD

**Issue by sigma1810** [zaquncio/rejony-app#27]
1. Wchodzę w Twój profil -> Zmień e-mail.
2. Podaję poprawny adres e-mail oraz niepoprawne hasło.

Próba zapisania błędu powoduje wyświetlenie komunikatu anglojęzycznego, mimo że korzystam z polskiej wersji językowej strony (bug).
![4](https://cloud.githubusercontent.com/assets/24360424/22906159/9ba80e4e-f243-11e6-92a9-1191cf2db83a.png)

**Comment by duzymaju** [comment]
Gotowe: #84.
