### ISSUE TITLE
Nie działa zmiana hasła

### ISSUE THREAD

**Issue by jakobos** [zaquncio/rejony-app#3]
Po otrzymaniu maila z linkiem do zmiany hasła i kliknięciu w niego wyświetla się wiadomość: "Podane żądanie zmiany hasła jest nieprawidłowe".

**Comment by sigma1810** [comment]
Opisanego błędu nie udało się powtórzyć na wesji strony 'Panel Rejonów' z dnia 2017-02-08.
Weryfikuję zgłoszenie.

**Comment by zaquncio** [comment]
Poprawiono
