### ISSUE TITLE
Brak możliwości zmiany hasła

### ISSUE THREAD

**Issue by tolamoon** [zaquncio/rejony-app#33]
Po wykonaniu zmiany z menu: 
Twój profil -> Zmień hasło ->
Ustawieniu nowego hasła wg. sugestii komunikatu nie wylogowałam się i kliknęłam w link aktywacyjny ->
Po czym wylogowałam się aby sprawdzić czy nowe hasło działa, ale wciąż działa stare(błąd) -> 
Dostaję komunikat "Nieprawidłowe dane logowania"

![zmiana_hasla](https://cloud.githubusercontent.com/assets/25660431/22925008/80e4700c-f2a7-11e6-9ca4-95f44cd0d70d.png)

**Comment by duzymaju** [comment]
Problem zostanie rozwiązany po zmianie, o której mowa w #31, więc zamykam ten issue.
