### ISSUE TITLE
Modyfikacja filtrowania i wyszukiwania rejonów

### ISSUE THREAD

**Issue by jakobos** [zaquncio/rejony-app#36]
**W Przestrzeni rejonu/Dane/Rejony i Dane/Zgłoszenia rejonów:**
- Należy przy filtrowaniu po terytorium dodać możliwość "--" - braku wybranego terytorium (kolor czerwony na screenie) 

**W Przestrzeni rejonu/Dane/Rejony:**
- Należy dodać możliwość wyszukiwania po kolumnie "Terytorium" (kolor zielony)
![1](https://cloud.githubusercontent.com/assets/25006353/22993802/9f701756-f3c4-11e6-851a-10f5cee2fd12.png)

**Comment by duzymaju** [comment]
Poprawka dodana: #102 (czeka na pull request).
