### ISSUE TITLE
Nie można usunąć rejonu z poziomu Rady EDK

### ISSUE THREAD

**Issue by marmeldev** [zaquncio/rejony-app#39]
Osoba z Rady EDK (login2) nie może usunąć rejonu ze statusem Nowe zgłoszenie i Weryfikacja mimo dostępności takiej opcji a kolumnie Akcje w Zgłoszenia projektów oraz po wejściu do projektu i wybranie Akcje -> Usuń.
![2017-02-16_00h24_23](https://cloud.githubusercontent.com/assets/25804236/23000134/572fd722-f3df-11e6-99ca-82fe658fd832.png)

**Comment by duzymaju** [comment]
Problem rozwiązany: #101.
