### ISSUE TITLE
Przestrzeń grupy: trasy - internal error

### ISSUE THREAD

**Issue by jakobos** [zaquncio/rejony-app#41]
Przy próbie kliknięcia w Przestrzeń Grupy/Dane/Trasy pojawia się Error 500.

**Comment by duzymaju** [comment]
Proszę o linka do miejsca występowania błędu - nie łapię się jeszcze dobrze w tym systemie.

**Comment by duzymaju** [comment]
OK, już widzę. Błąd usunięty - winny był brak jednego "use", a następnie złe warunki przy braku wyników zapytań w encji grupy.
