### ISSUE TITLE
Próba logowania - internal error 500

### ISSUE THREAD

**Issue by sigma1810** [zaquncio/rejony-app#45]
Próba zalogowania zakończyła się błędem internal error 500 (szczegóły na zrzucie ekranu).

![blad](https://cloud.githubusercontent.com/assets/24360424/23091524/796d8a5c-f5b8-11e6-9322-baf9adfffb52.png)

**Comment by duzymaju** [comment]
Naprawione: https://github.com/zaquncio/rejony-app/pull/60.

**Comment by duzymaju** [comment]
Teraz w przypadku braku zgłoszenia o podanym ID wyświetlany jest stosowny komunikat zamiast błędu 50.
