### ISSUE TITLE
Tworzenie nowej grupy - pusta lista rozwijana

### ISSUE THREAD

**Issue by sigma1810** [zaquncio/rejony-app#47]
Z poziomu konta administratora wchodzę w: Przestrzeń projektu ->Dane -> Grupy.
Selektor "Kategoria" jest pusty. Czy to jest OK?
![pytanie](https://cloud.githubusercontent.com/assets/24360424/23092206/13b6d69c-f5c6-11e6-86ef-a980128f7d34.png)

**Comment by jakobos** [comment]
Jest ok, bo nie ma żadnych kategorii stworzonych.

**Comment by sigma1810** [comment]
Potwierdzam.
