### ISSUE TITLE
Błąd pzy próbie wejścia w trasy - konto użytkownika( na adminie jest OK)

### ISSUE THREAD

**Issue by sigma1810** [zaquncio/rejony-app#48]
Próba wejścia w 'Trasy' z panelu bocznego
![trasy](https://cloud.githubusercontent.com/assets/24360424/23095233/d6868790-f606-11e6-8fb5-1e29aaddf528.png)
 kończy się błędem 'Internal error 500' (zwykły użytkownik).
![blad](https://cloud.githubusercontent.com/assets/24360424/23095197/38935126-f606-11e6-8250-41f46c4fb564.png).
Użytkownik ma zatwierdzone 3 rejony i niezależnie od wyboru rejonu wejście w zakładkę 'Trasy' powoduje wystąpienie ww błędu.

Na koncie administratora problem już nie występuje.

**Comment by duzymaju** [comment]
Poprawione: #98.
