### ISSUE TITLE
Przestrzeń grupy -> Wyniki szkoleń - "internal error 500"

### ISSUE THREAD

**Issue by sigma1810** [zaquncio/rejony-app#51]
Zwykły użytkownik (nie admin) akceptuje zaproszenie do grupy i przechodzi w przestrzeń grupy.
Wybranie Przestrzeń grupy -> Wyniki szkoleń  powoduje wyświetlenie błędu "internal error 500".
![blad](https://cloud.githubusercontent.com/assets/24360424/23095453/5b0bb21c-f60a-11e6-888b-4dc4b36250ad.png)
![blad cd](https://cloud.githubusercontent.com/assets/24360424/23095457/614c6eaa-f60a-11e6-8f68-886cc88251ef.png)

**Comment by duzymaju** [comment]
Problemem był błąd w nazwie serwisu `cantiga.user.membership.storage`.
