### ISSUE TITLE
Szczegóły rejonu ->Zarządzaj -> Statystyki uczestników - "Internal error 500"

### ISSUE THREAD

**Issue by sigma1810** [zaquncio/rejony-app#53]
Konto administratora.
Przechodzę do: Przestrzeń projektu -> Dane -> Rejony ->Szczegóły rejonu.
Wybieram: Zarządzaj -> Statystyki uczestników:
![blad](https://cloud.githubusercontent.com/assets/24360424/23095554/0aa5667c-f60c-11e6-966c-6e08f2326a54.png)
Pojawia się błąd "Internal error 500":
![blad cd](https://cloud.githubusercontent.com/assets/24360424/23095557/1c0789ae-f60c-11e6-889a-663cbbec415e.png)

**Comment by duzymaju** [comment]
Hmmm... `You have requested a non-existent service "cantiga.core.repo.project_area".` - nie mam pojęcia, z jakiego powodu to repozytorium nie jest serwisem - pozostawiam do rozwiązania autorowi.

**Comment by zaquncio** [comment]
Co nie jest serwisem cantiga.core.repo.project_area?

**Comment by duzymaju** [comment]
W `CoreBundle` wśród repozytoriów znajduje się `ProjectAreaRepository`, do którego prawdopodobnie chciano się tu odwołać, ale w `CoreBundle/Resources/config/services.yml` nie zdefiniowano (z niewiadomych mi przyczyn - być może celowo, a być może nie) dla tego repozytorium serwisu, więc `cantiga.core.repo.project_area` nie istnieje.

**Comment by duzymaju** [comment]
Zmieniłem `@cantiga.core.repo.project_area` na `@cantiga.core.repo.area_mgmt` i odpowiednie routingi (serwis `ProjectAreaRepository` stał się częścią `AreaMgmtRepository`).
