### ISSUE TITLE
Rejony - brak translacji na j.polski

### ISSUE THREAD

**Issue by sigma1810** [zaquncio/rejony-app#54]
Konto administratora.
Po wejściu w szczegóły danego rejonu w nagłówku pojawia się anglojęzyczny opis (strona ustawiona na wersję językową).
![blad](https://cloud.githubusercontent.com/assets/24360424/23095585/8132df18-f60c-11e6-96ac-d6ecbab28827.png)

**Comment by duzymaju** [comment]
Gotowe: #84.
