### ISSUE TITLE
Można przypisać więcej niż 5 'Rejonów' do 'Grupy Rejonów'

### ISSUE THREAD

**Issue by sigma1810** [zaquncio/rejony-app#55]
W obrębie pojedynczej Grupy Rejonów można dodać więcej niż 5 Rejonów - zgodnie z dostarczoną dokumentacją jest to błąd.
![blad](https://cloud.githubusercontent.com/assets/24360424/23095642/53ad34de-f60d-11e6-844a-6d8535a04017.png)

Proszę o wprowadzenie ograniczenia.

**Comment by jakobos** [comment]
Być może dokumentacja jest trochę nieścisła, liczba rejonów w grupie jest zmienna, dopuszczamy żeby było ich więcej.
