### ISSUE TITLE
Rejony: "Podany element nie został znaleziony"

### ISSUE THREAD

**Issue by sigma1810** [zaquncio/rejony-app#56]
1. W przestrzeni projektu przechodzę do Zestawienia ->Kamienie milowe.
![1](https://cloud.githubusercontent.com/assets/24360424/23100486/66f77fd4-f682-11e6-8ebb-5649a6403700.png)
2. Wybieram [Zobacz grupy].
![2](https://cloud.githubusercontent.com/assets/24360424/23100488/9a45dd9a-f682-11e6-8e8b-8c2bf9c7e7d1.png)
3. Wybieram jedną z grup.
![2](https://cloud.githubusercontent.com/assets/24360424/23100498/dbedeca6-f682-11e6-90b6-3319b11b4cbf.png)

System zamiast przenieść użytkownika do Grupy wyświetla błąd jak na poniższym zrzucie ekranu i przenosi usera do sekcji Dane ->Rejony (błąd).
![2](https://cloud.githubusercontent.com/assets/24360424/23100500/ff06f340-f682-11e6-8766-5be3ac286272.png)

**Comment by duzymaju** [comment]
Rozwiązane (błędny routing w linku): #87.
