### ISSUE TITLE
Członkowie Grupy - brak translacji na j.polski

### ISSUE THREAD

**Issue by sigma1810** [zaquncio/rejony-app#57]
Wchodzę w szczegóły Grupy i wybieram Zarządzaj -> Członkowie.
![2](https://cloud.githubusercontent.com/assets/24360424/23100558/b489a0fe-f684-11e6-8610-31bc764eefda.png)

1. Proszę o dodanie translacji dla pkt. 1-2 zaznaczonych na poniższych zrzutach ekranu,
![2](https://cloud.githubusercontent.com/assets/24360424/23100576/fa87d422-f684-11e6-919f-2f1611d61e18.png)
oraz pkt 3-4 po wejściu w 'Change role'
![2](https://cloud.githubusercontent.com/assets/24360424/23100584/52c593e0-f685-11e6-84b5-b5c871aaad19.png)

**Comment by duzymaju** [comment]
Poprawione: #84.
