### ISSUE TITLE
Nie można przypisać koordynatora Grupy

### ISSUE THREAD

**Issue by sigma1810** [zaquncio/rejony-app#58]
1. Wchodzę w szczegóły Grupy.
![2](https://cloud.githubusercontent.com/assets/24360424/23101106/6cd1e6dc-f68d-11e6-9fd1-35a8f3098fbf.png)
2. Wybieram Zarządzaj -> Członkowie.
![2](https://cloud.githubusercontent.com/assets/24360424/23101115/89b8df62-f68d-11e6-9a5b-c8e4d9238a08.png)

Zarówno przy zapraszaniu nowego użytkownika do Grupy
![2](https://cloud.githubusercontent.com/assets/24360424/23101628/2c1f2586-f698-11e6-9ff0-b35b2e4ce4b0.png)
jak i po wejściu w edycję dodanego już do grupy użytkownika 
![2](https://cloud.githubusercontent.com/assets/24360424/23101638/5dc1df34-f698-11e6-9bb3-e19ae4273ea1.png)
jako rolę można wybrać tylko 'Członek(Member)'. Nie ma możliwości wskazania roli 'Koordynator' dla koordynatora Grupy (bug).

**Comment by jakobos** [comment]
Koordynator Grupy to jest rola zewnętrzna w EDK, w grupie wszyscy są członkami.
