### ISSUE TITLE
Aktualizacja mapy w szczegółach trasy

### ISSUE THREAD

**Issue by jakobos** [zaquncio/rejony-app#74]
Po wgraniu trasy razem ze śladem, na mapie wyświetla się ślad, jednak po podmianie pliku śladu na nowy, na mapie dalej widoczny jest stary ślad.
Np. w Przestrzeń rejonu/Rejon/Trasy -> "Info"

**Comment by duzymaju** [comment]
Poprawione: #73. @zaquncio: Jeśli to rozwiązuje sprawę, zamknij proszę tego taska.

**Comment by zaquncio** [comment]
poprawione
