### ISSUE TITLE
Błąd podczas wysyłania wiadomości do rejonu

### ISSUE THREAD

**Issue by zaquncio** [zaquncio/rejony-app#77]
http://beta.edk.org.pl/pub/edk/Eb2qrCBtKDlQ/napisz-wiadomosc/formularz

próba wysłania kończy się błędem .

**Comment by duzymaju** [comment]
Poprawione: #82. Usiedziałem się nad rozwiązaniem tego problemu mnóstwo czasu aż w końcu zauważyłem, z jakiej innej metody mogę skorzystać. Rozumiem, że problem wiązał się ze zmianą wersji systemu Cantiga.
Niestety choć wiadomości dodają się teraz prawidłowo, próba zobaczenia ich szczegółów również powoduje błąd 500: #83.
