### ISSUE TITLE
Błąd podczas odczytu wiadomości

### ISSUE THREAD

**Issue by duzymaju** [zaquncio/rejony-app#83]
ścieżka dostępu: Przestrzeń rejonu > Uczestnicy > Wiadomości > "info" przy konkretnej wiadomości na liście
Otwarcie widoku szczegółów wiadomości (akcja `area_edk_message_info`) wywala błąd 500, ponieważ w `EdkMessageRepository::getItem()` wykorzystywana jest metoda `EdkMessage::fetchByRoot()`, do której przekazywana jest encja `Area`, tyle że `fetchByRoot` wymaga tam interfejsu `MembershipEntityInterface`, którego `Area` nie implementuje. Jest to wg mnie jednak błąd w samym systemie Cantiga (chyba że czegoś nie widzę), bo wewnątrz `fetchByRoot` jest odniesienie zarówno do `Area` jak i do `Group` oraz `Project` - żadna z tych encji nie implementuje w/w interfejsu, więc jest tu moim zdaniem spora niespójność i trzeba byłoby rozwiązać problem na tym poziomie.

**Comment by zyxist** [comment]
Prawidłowym interfejsem jest teraz `HierarchicalInterface`. W oryginalnej wersji nie było żadnego takiego interfejsu i ten `MembershipEntityInterface` był trochę bez sensu wykorzystywany poza swoim oryginalnym zastosowaniem.

Ogólnie obecnie implementacja `MembershipEntityInterface` jest w encji `Place`, zaś jeśli potrzebujecie projektu, grupy lub rejonu, to typem dla Was będzie `HierarchicalInterface`.

**Comment by duzymaju** [comment]
OK, dzięki - zmieniam interfejs w `EdkMessage::fetchByRoot()` na `HierarchicalInterface`. Poprawione: #91.
