### ISSUE TITLE
Nie działa zmiana ustawień języka strony

### ISSUE THREAD

**Issue by sigma1810** [zaquncio/rejony-app#9]
1. Przechodzę do: Strona główna ->Twój porfil -> Ustawienia - w selektorze 'Język strony' mam ustawiony 'Polski'.
2. Zmieniam język na 'English' i zapisuję zmiany (przycisk [Zapisz]).
Dostaję komunikat "Ustawienia twojego profilu zostały zmienione", jednak sama strona pozostaje w języku polskim i nie odświeża się do wersji anglojęzycznej (bug).
Odświeżenie Ctrl + F5 róœnież nie pomaga.
Problem rozwiązuje ponowne przelogowanie się do konta.

Proszę o autoodświeżenie strony do wersji anglojęzycznej bezpośrednio po zapisaniu zmian przyciskiem [Zapisz].

Problem dotyczy również okna logowania: po zmianie języka, zapisaniu zmian i wylogowaniu się z konta okno logowania nie odswieża się do ustawionej wersji językowej (bug).

**Comment by duzymaju** [comment]
#72 - naprawione
