### ISSUE TITLE
Lista uczestników: brak możliwości edycji

### ISSUE THREAD

**Issue by jakobos** [zaquncio/rejony-app#90]
Przestrzeń rejonu/Uczestnicy/Uczestnicy

Przy próbie edycji danych zapisanego użytkownika, nie działa przycisk "Zmień dane".
Na panelu beta dodatkowo po kliknięciu "Zmień dane" pojawia się error 500.

**Comment by duzymaju** [comment]
Naprawione (tak mi się zdaje - trzeba przetestować tak dodawanie jak i edycję uczestnika w panelu): #95. Proszę o zamknięcie taska po zaakceptowaniu pull requesta.
